---
title: "Apteryx rowi analysis"
author: "J Taylor"
date: "2024-03-17"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=TRUE, echo=FALSE, results='hide'}
knitr::opts_chunk$set(echo = TRUE)

# Required packages
packages_to_install <- c("vegan", "tidyverse", "ggplot2", "reshape2")

# Install packages if not present 
for (package in packages_to_install) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package, dependencies = TRUE)
  }
}

# Load packages
library(vegan)
library(tidyverse)
library(ggplot2)

rm(packages_to_install, package)
```

```{r load-files, include=FALSE, message=FALSE, warning=TRUE, echo=FALSE, results='hide'}

# Load in abundance and metadata file
data <- read.csv(file = "CCMetagen_merged_abundance.csv", header = TRUE, na.strings = c("", "NA", "N/A"), stringsAsFactors = FALSE)

# Load in Kiwi metadata file
library(dplyr)
metadata <- read.csv(file = "viral_abundance.csv", header = TRUE, stringsAsFactors = TRUE)
metadata <- mutate(metadata, reads = as.numeric(gsub(",", "", reads))) # Remove digit grouping separator
```

```{r RPM-normalisation, echo=FALSE}
# Load dplyr package
library(dplyr)

# Normalise count data into reads per million (RPM)
reads <- metadata$reads
normalised_data <- data[, 1:42] # Extract samples PK1 to PK42
normalised_data <- sweep(normalised_data, 2, reads, "/") * 1e6 # RPM Normalisation: (abundance / total reads) * 1e6
normalised_data <- cbind(normalised_data, data[, 43:ncol(data)]) # Rebind taxonomic metadata onto new df

# Clear values
rm(reads)
```

```{r NMDS-Genus-level-PREPARE, echo=FALSE, message=FALSE, warning=FALSE}
# Prepare dataframe for NMDS
data_working <- normalised_data %>% 
  filter(!is.na(Genus)) %>% # Remove any taxa that doesn't have at least Genus level classification
  mutate(taxonomy = ifelse(Genus != "unk_g", paste(Superkingdom, Genus, sep = ";"),
                           paste(Superkingdom, Kingdom, Phylum, Class, Order, Family, Genus, sep = ";"))) %>% 
  select(-c(Superkingdom, Kingdom, Phylum, Class, Order, Family, Genus)) %>% 
  select(c(taxonomy, everything()))

data_working <- aggregate(. ~ taxonomy, data = data_working, FUN = sum, na.rm = TRUE)
rownames(data_working) <- data_working$taxonomy
nmds_data_genus <- data_working[,-1]
nmds_norm_data = sweep(nmds_data_genus[,1:42], 1, rowSums(nmds_data_genus[,1:42]),"/") # Prepare nmds dataframe for vdist
nmds_input <- t(nmds_norm_data) # Transpose sample and taxonomy

library(dplyr)

# Clean up
rm(data_working, nmds_data_genus)

columns_to_select <- c("sample_type", "pool", "health_status", "participant_id", "participant_name")

# Match row names in nmds_input with library column in metadata and select specific columns
nmds_norm_data <- merge(metadata[, c("library", columns_to_select)], nmds_input, by.x = "library", by.y = 0, all.x = TRUE)

# NMDS distance matrix 
library(vegan)

set.seed(1095)

vdist=vegdist(nmds_norm_data[, -c(1:6)], "bray")

nmds <- metaMDS(vdist, distance = "bray", try = 10000, trymax = 10000, k = 2, wascores = TRUE)
```

```{r NMDS-Genus-level-RUN}
# Check stress and basic distribution of NMDS points
stressplot(nmds)
plot(nmds, type='p', display=c('site', 'species'))

# extract nmds plotting values for ggplot
nmds_points = as.data.frame(nmds$points) # Extract MDS1 and MDS2
nmds_points = cbind(nmds_points, nmds_norm_data[, 1:6]) # Rebind sample metadata

# Adonis2 analysis
adonis2(formula = vdist~sample_type, data = nmds_points, method = "bray")
adonis2(formula = vdist~health_status, data = nmds_points, method = "bray")
adonis2(formula = vdist~participant_id, data = nmds_points, method = "bray")
adonis2(formula = vdist~participant_name, data = nmds_points, method = "bray")

library(ggplot2)

# == Genus-Level
genus_level_NMDS <- ggplot(
  nmds_points, aes(x = MDS1, y = MDS2, colour = health_status, shape = sample_type)) +
  geom_point(size = 2.9, alpha = 0.9) +
  labs(title = NULL, x = "MDS1", y = "MDS2", colour = "Health Status", shape = "Sample Type") +
  theme_minimal() +
  theme(legend.position = "right", panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1) ) +
  scale_color_manual(values = c("Normal" = "#5DBA48", "Mild" = "#3C80C3", "Moderate" = "#DFA628", "Severe" = "#E0214B")) +
  scale_shape_manual(values = c("Oral swab" = 16, "Cloacal swab" = 17, "Skin biopsy" = 3)) +
  guides(color = guide_legend(title = "Health Status"), shape = guide_legend(title = "Sample Type")
         )
genus_level_NMDS
ggsave("genus_NMDS.svg", plot = genus_level_NMDS, width = 8, height = 8, units = "in", device = "svg")

genus_HealthStatus_NMDS <- ggplot(
  nmds_points, aes(x = MDS1, y = MDS2, colour = health_status, shape = sample_type)) +
  geom_point(size = 2.9, alpha = 0.6) +
  labs(title = NULL, x = "MDS1", y = "MDS2", colour = "Health Status", shape = "Sample Type", caption = "NMDS plot showing genus-level community structure and the relationship among different \nsample types and Health Status") +
  theme_minimal() +
  theme(legend.position = "right", panel.grid.minor = element_blank()) +
  scale_color_manual(values = c("Normal" = "#5DBA48", "Mild" = "#3C80C3", "Moderate" = "#DFA628", "Severe" = "#E0214B")) +
  scale_shape_manual(values = c("Oral swab" = 16, "Cloacal swab" = 17, "Skin biopsy" = 3)) +
  guides(color = guide_legend(title = "Health Status"), shape = guide_legend(title = "Sample Type")) +
  facet_wrap(~ health_status, scales = "free")

genus_HealthStatus_NMDS
#ggsave("genus_HealthStatus_facet_NMDS.svg", plot = genus_HealthStatus_NMDS, width = 8, height = 8, units = "in", device = "svg")

```
# rm(nmds_norm_data, nmds)

```{r composition-table}
library(dplyr)

# Keep the relevant columns for calculating proportions
proportion_data <- normalised_data %>% 
  filter(!is.na(Genus), Phylum != "Chordata", Superkingdom != "Viruses", Kingdom != "Viridiplantae") %>%
  mutate(taxonomy = ifelse(Genus != "unk_g", paste(Superkingdom, Genus, sep = ";"),
                           paste(Superkingdom, Kingdom, Phylum, Class, Order, Family, Genus, sep = ";"))) %>% 
  select(-c(Superkingdom, Kingdom, Phylum, Class, Order, Family, Genus)) %>% 
  select(c(taxonomy, everything()))

# Aggregate the data by taxonomy
aggregated_data <- aggregate(. ~ taxonomy, data = proportion_data, FUN = sum)

rownames(aggregated_data) <- aggregated_data$taxonomy

aggregated_data <- aggregated_data[,-1]

aggregated_data <- t(aggregated_data)

columns_to_select <- c("sample_type", "pool", "health_status", "participant_id", "participant_name")
aggregated_data <- merge(metadata[, c("library", columns_to_select)], aggregated_data, by.x = "library", by.y = 0, all.x = TRUE)

aggregated_data <- aggregated_data %>% 
  select(-c(health_status, pool, participant_id, participant_name))


# Convert the library column to a factor with custom levels
aggregated_data$library <- factor(aggregated_data$library)

# Sort the data frame based on the custom levels
sorted_data <- aggregated_data[order(aggregated_data$library), ]

sorted_indices <- order(-colSums(sorted_data[, 3:ncol(sorted_data)], na.rm = TRUE))
sorted_df <- sorted_data[, c(1:2, sorted_indices + 2)]

column_sums <- colSums(sorted_data[, 3:ncol(sorted_data)], na.rm = TRUE)

# Find the top 20 values and their indices
top_20_values <- head(sort(column_sums, decreasing = TRUE), 20)
top_20_indices <- match(top_20_values, column_sums)

print(top_20_values)
print(top_20_indices)

# Prepare dataframes
subset_20 <- sorted_df[, 1:22]

subset_norm_20 <- sweep(subset_20[, 3:ncol(subset_20)], 1, rowSums(subset_20[, 3:ncol(subset_20)]), "/")
subset_norm_20 <- subset_20
subset_norm_20[, 3:ncol(subset_20)] <- sweep(subset_20[, 3:ncol(subset_20)], 1, rowSums(subset_20[, 3:ncol(subset_20)]), "/")

library(ggplot2)
library(reshape2)

melted_data <- melt(subset_norm_20, id.vars = c("library", "sample_type"))

stacked_abundance <- ggplot(melted_data, aes(x = library, y = value * 100, fill = variable)) +
  geom_bar(stat = "identity") +
  labs(title = "Proportional Abundance of Taxa Across Libraries",
       x = "Library",
       y = "Proportion (%)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "bottom") +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  coord_flip()

print(stacked_abundance)

#ggsave("composition_bargraph_abundance_20.svg", plot = stacked_abundance, width = 20, height = 13, units = "in", device = "svg")
```

